#!/bin/bash
# v6.3

# Set log file paths
LOGFILE="/home/logs/UDC/UpdateNClean.log-$(date +%m.%d.%y)"
LOGFILE2="/home/logs/rkhunter/RKhunter.log-$(date +%m.%d.%y)"
LOGFILE3="/home/logs/clamav/ClamAV.log-$(date +%m.%d.%y)"
ERRORLOG="/home/logs/UDC/UDC-ERRORS/UDC-ERROR-Log-$(date +%m.%d.%y_%H.%M.%S)"

# Function to log errors
log_error() {
    echo "[ERROR] $(date "+%T"):   $1" >> "$ERRORLOG"
}

# Function to check exit status of the previous command
check_exit_status() {
    if [ $? -eq 0 ]; then
        echo
        echo "          ^ Process Completed ^" >> "$LOGFILE"
        echo
    else
        echo
        echo "          ^ [ERROR] Process Failed! ^" >> "$LOGFILE"
        log_error "Process failed!"
        echo
    fi
}

# Function to perform the update process
update() {
    echo "** Update Time and Date **"
    echo "$(date "+%T") :   - Update Time and Date" >> "$LOGFILE" 2>&1
    sudo ntpdate pool.ntp.org
    check_exit_status

    echo "** Update package lists for upgrades **"
    echo "$(date "+%T") :   - Update package lists for upgrades" >> "$LOGFILE" 2>&1
    sudo apt-get update
    check_exit_status

    echo "** Upgrade System to new release (if Available) **"
    echo "$(date "+%T") :   - Upgrade System to new release (if Available)" >> "$LOGFILE" 2>&1
    sudo do-release-upgrade -f DistUpgradeViewNonInteractive >> "$LOGFILE" 2>&1
    check_exit_status

    echo "** Update ClamAV (if necessary) **"
    echo "$(date "+%T") :   - Update ClamAV (if necessary)" >> "$LOGFILE" 2>&1
    if ! command -v clamscan &>/dev/null; then
        echo "ClamAV is not installed. Please install ClamAV first."
        exit 1
    fi
    current_version=$(clamscan --version | awk '{print $NF}')
    latest_version=$(wget -qO- https://www.clamav.net/downloads | grep -Eo 'ClamAV [0-9]+\.[0-9]+\.[0-9]+' | awk '{print $NF}')
    echo "Current version:   $current_version"
    echo "Latest version:   $latest_version"

    if [[ $current_version == $latest_version ]]; then
        echo "ClamAV is already up to date."
    else
        sudo apt-get install --only-upgrade clamav -y
        echo "ClamAV has been updated to the latest version."
    fi

    check_exit_status
    echo
    echo "** Update virus database **"
    sudo /etc/init.d/clamav-freshclam stop
    sudo freshclam
    check_exit_status
    sudo /etc/init.d/clamav-freshclam start
}

# Function to perform housekeeping tasks
housekeeping() {
    echo "$(date "+%m/%d/%Y @ %T") :   CLEANING" >> "$LOGFILE"
    echo "*--------------------------------------*"
    echo "*            HOUSEKEEPING!            *"
    echo "*--------------------------------------*"

    echo "** Clean up Kernels **"
    KEEP=2
    CANDIDATES=$(ls -tr /boot/vmlinuz-* | head -n -${KEEP} | grep -v "$(uname -r)" | cut -d- -f2- | awk '{print "linux-image-" $0 " linux-headers-" $0}')
    for c in $CANDIDATES; do
        dpkg-query -s "$c" >/dev/null 2>&1 && PURGE="$PURGE $c"
    done

    if [ -z "$PURGE" ]; then
        echo "No kernels are eligible for removal"
    fi
    sudo apt-get remove -y --purge $PURGE
    check_exit_status
}

# Main script execution
{
    echo
    echo "==========================================="
    echo "       -:  :   Update & Clean v6.3 :  :  -"
    echo "==========================================="
    echo "$(date "+%m/%d/%Y @ %T") :   ******** Update & Clean Script Started! ********" >> "$LOGFILE"

    update
    housekeeping

    echo "$(date "+%m/%d/%Y @ %T") :   ******** Update & Clean Script Completed! ********" >> "$LOGFILE"
} 2>> "$ERRORLOG"
